### ISSUE TITLE
Many Error while Compiling in Node.js 4.0

### ISSUE THREAD

**Issue by tommyZZM** [mikeseven/node-opencl#25]
error C2665: “Nan::New”: none of the 11 overloads can convert parameter from type 'type'

error C2039: 'SetIndexedPropertiesToExternalArrayData'  is not a member of 'v8::Object' 

error C2039: 'GetIndexedPropertiesToExternalArrayData'  is not a member of 'v8::Object' 

error C2039: 'kExternalByteArray' is not a member of 'v8' 

i m in **master** branch

**Comment by mikeseven** [comment]
It is not merged in master branch yet.
Use feature/node4 branch.

On Sep 28, 2015 6:44 PM, tommyZZM <notifications@github.com> wrote:

error C2665: “Nan::New”: none of the 11 overloads can convert parameter from type 'type'

error C2039: 'SetIndexedPropertiesToExternalArrayData' is not a member of 'v8::Object'

error C2039: 'GetIndexedPropertiesToExternalArrayData' is not a member of 'v8::Object'

error C2039: 'kExternalByteArray' is not a member of 'v8'
