### ISSUE TITLE
Compile using Microsoft Visual Studio 2015

### ISSUE THREAD

**Issue by tommyZZM** [mikeseven/node-opencl#27]
if you see this error while using Microsoft Visual Studio 2015
LINK : fatal error LNK1104: cannot open file 'libcpmt.lib'

**solution**
````
npm install --msvs_version=2015
````

**Comment by mikeseven** [comment]
This is Microsoft library. Likely a bad installation of Visual Studio 2015 and/or node.
Possibly confusion between 32b and 64b libraries, OpenCL SDK on your system etc…

On Oct 5, 2015, at 9:41 PM, tommyZZM <notifications@github.com<mailto:notifications@github.com>> wrote:


if you see this error while using Microsoft Visual Studio 2015
LINK : fatal error LNK1104: cannot open file 'libcpmt.lib'

solution

npm install --msvs_version=2015
