### ISSUE TITLE
CreateCommandQueueWithProperties sometimes fails

### ISSUE THREAD

**Issue by milhidaka** [mikeseven/node-opencl#36]
CreateCommandQueueWithProperties sometimes fails without reproducibility.
I investigated and https://www.khronos.org/registry/cl/sdk/2.0/docs/man/xhtml/clCreateCommandQueueWithProperties.html says argument properties have to be terminated with 0.

In my environment (Ubuntu 14.04 + AMD APP SDK 3.0), this patch solved the problem. Please consider fixing the code.

    diff --git a/src/commandqueue.cpp b/src/commandqueue.cpp
    index 6079590..4de5eb1
    --- a/src/commandqueue.cpp
    +++ b/src/commandqueue.cpp
    @@ -79,6 +79,7 @@ NAN_METHOD(CreateCommandQueueWithProperties) {
           THROW_ERR(CL_INVALID_QUEUE_PROPERTIES)
         }
       }
    +  cl_properties.push_back(0);
     
       cl_int err;
       cl_command_queue q = ::clCreateCommandQueueWithProperties(

**Comment by mikeseven** [comment]
thanks!
