### ISSUE TITLE
binding.gyp in linux

### ISSUE THREAD

**Issue by milhidaka** [mikeseven/node-opencl#37]
In linux, environment variable should be used with "$". Please consider fixing it.

    diff --git a/binding.gyp b/binding.gyp
    index 912d172..6a4f120 100644
    --- a/binding.gyp
    +++ b/binding.gyp
    @@ -44,7 +44,7 @@
             ['OS in "linux freebsd openbsd solaris android"', {
               'variables' : {
                 # AMD APP SDK
    -            'OPENCL_SDK' : '<!(echo %AMDAPPSDKROOT%)',
    +            'OPENCL_SDK' : '<!(echo $AMDAPPSDKROOT)',
                 'OPENCL_SDK_INCLUDE' : '<(OPENCL_SDK)/include',
                 'OPENCL_SDK_LIB' : '<(OPENCL_SDK)/lib/x86_64',
               },

**Comment by mikeseven** [comment]
fixed, thanks!
