### ISSUE TITLE
Error when giving 2^31 to 2^32 value to kernel argument of type uint

### ISSUE THREAD

**Issue by milhidaka** [mikeseven/node-opencl#45]
input checking may have to be corrected

```diff
diff --git a/src/kernel.cpp b/src/kernel.cpp
index 3a7190a..24284f2 100644
--- a/src/kernel.cpp
+++ b/src/kernel.cpp
@@ -128,7 +128,7 @@ public:
     CONVERT_NUMBER("short", cl_short, IsInt32, ToInt32()->Value);
     CONVERT_NUMBER("ushort", cl_ushort, IsInt32, ToUint32()->Value);
     CONVERT_NUMBER("int", cl_int , IsInt32, ToInt32()->Value);
-    CONVERT_NUMBER("uint", cl_uint, IsInt32, ToUint32()->Value);
+    CONVERT_NUMBER("uint", cl_uint, IsUint32, ToUint32()->Value);
     CONVERT_NUMBER("long", cl_long, IsNumber, ToInteger()->Value);
     CONVERT_NUMBER("ulong", cl_ulong, IsNumber, ToInteger()->Value);
     CONVERT_NUMBER("float", cl_float, IsNumber, NumberValue);
```

**Comment by mikeseven** [comment]
Thanks

--mike



On Thu, May 12, 2016 at 6:47 PM -0700, "milhidaka" <notifications@github.com<mailto:notifications@github.com>> wrote:


input checking may have to be corrected

diff --git a/src/kernel.cpp b/src/kernel.cpp
index 3a7190a..24284f2 100644
--- a/src/kernel.cpp
+++ b/src/kernel.cpp
@@ -128,7 +128,7 @@ public:
     CONVERT_NUMBER("short", cl_short, IsInt32, ToInt32()->Value);
     CONVERT_NUMBER("ushort", cl_ushort, IsInt32, ToUint32()->Value);
     CONVERT_NUMBER("int", cl_int , IsInt32, ToInt32()->Value);
-    CONVERT_NUMBER("uint", cl_uint, IsInt32, ToUint32()->Value);
+    CONVERT_NUMBER("uint", cl_uint, IsUint32, ToUint32()->Value);
     CONVERT_NUMBER("long", cl_long, IsNumber, ToInteger()->Value);
     CONVERT_NUMBER("ulong", cl_ulong, IsNumber, ToInteger()->Value);
     CONVERT_NUMBER("float", cl_float, IsNumber, NumberValue);

-
